# Generated by Django 6.0.2 on 2026-03-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_greeting_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='image',
            field=models.ImageField(default='', upload_to='greetings'),
            preserve_default=False,
        ),
    ]
